---
title: "Introduction to the survcomp2 Package"
author: "Jian He"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{survcomp2_Vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(survcomp2)
```

```{r}
path <- system.file("extdata", "bcsurg.csv", package = "survcomp2")
dat <- read.csv(path)
```

```{r}
str(dat)
```

```{r fig.height=12.5, fig.width=7.03, fig.align="center"}
survcomp_plot(dat = dat, patid = "ID..", 
              f1 = "Groups", f2 = "Breast_surgery_code",
              dt_start = "DT_dxdate2",
              dt_outcome = "DT_dod", 
              dt_end = "DT_date_last_seen")
```

```{r}
emm_contrasts <- survcomp(dat = dat, patid = "ID..",
                          x_c = c("Groups", "Breast_surgery_code"),
                          x_n = "AGE_agedx", dt_start = "DT_dxdate2",
                          dt_outcome = "DT_dod",
                          dt_end = "DT_date_last_seen")
```

```{r}
emm_contrasts[emm_contrasts$p.value < 0.05, ]
```


```{r}
pwcomp_output_df <- data.frame(
  contrast = emm_contrasts$contrast,
  factor2 = emm_contrasts$Breast_surgery_code,
  hazard_ratio = round(emm_contrasts$ratio, 3),
  standard_error = round(emm_contrasts$SE, 3),
  dof = emm_contrasts$df,
  #lower_limit = emm_contrasts$asymp.LCL,
  #upper_limit = emm_contrasts$asymp.UCL,
  #null_hyp = emm_contrasts$null,
  #test_stat = emm_contrasts$z.ratio,
  p = round(emm_contrasts$p.value, 3)
)
pwcomp_output_df
```

